language: ruby
sudo: true

rvm:
  - 2.5.3

services:
  - postgresql

before_install:
  - gem update --system
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - mv config/travis.master config/master.key
  - rm config/credentials.yml.enc
  - mv config/travis.credentials config/credentials.yml.enc
script:
  - xvfb-run -a bundle exec rspec