language: ruby
sudo: true

rvm:
  - 2.5.3

services:
  - postgresql
  - redis-server
addons:
  chrome: stable

before_install:
  - gem update --system
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - rm config/storage.yml
  - mv config/storage.yml.travis config/storage.yml
  - rm config/initializers/devise.rb
  - mv config/devise.rb.travis config/initializers/devise.rb
  - sudo apt-get install sphinxsearch
script:
  - xvfb-run -a bundle exec rake ts:configure
  - xvfb-run -a bundle exec rake ts:index
  - xvfb-run -a bundle exec rake ts:start
  - xvfb-run -a bundle exec rspec/spec --color --tty